import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Silk Slip Dress",
    brand: "House of CB",
    category: "dress",
    occasion: "party",
    images: [
      "/images/women-dresses/wd_3.jpg",
    ],
    rentalPrice: { perDay: 499, per3Days: 1199, perWeek: 1999 },
    retailPrice: 12000,
    sizes: ["XS", "S", "M", "L"],
    description:
      "Draped in pure silk with a fluid silhouette, this slip dress transitions effortlessly from a rooftop gathering to a gallery opening.",
    available: true,
    tags: ["silk", "evening", "minimalist"],
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "2",
    name: "Structured Blazer Dress",
    brand: "Reformation",
    category: "dress",
    occasion: "work",
    images: [
      "/images/women-dresses/wd_4.jpg",
    ],
    rentalPrice: { perDay: 599, per3Days: 1499, perWeek: 2499 },
    retailPrice: 18000,
    sizes: ["S", "M", "L", "XL"],
    description:
      "A power-dressing essential. Tailored lapels and a relaxed hem create the perfect balance of authority and ease.",
    available: true,
    tags: ["blazer", "formal", "tailored"],
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "3",
    name: "Floral Maxi Dress",
    brand: "Zimmermann",
    category: "dress",
    occasion: "wedding",
    images: [
      "/images/women-dresses/wd_5.jpg",
    ],
    rentalPrice: { perDay: 799, per3Days: 1999, perWeek: 3299 },
    retailPrice: 28000,
    sizes: ["XS", "S", "M"],
    description:
      "Cascading botanicals on a flowing chiffon base. Made for ceremonies where every moment is photographed.",
    available: true,
    tags: ["floral", "maxi", "wedding guest"],
    rating: 4.9,
    reviewCount: 203,
  },
  {
    id: "4",
    name: "Classic Trench Coat",
    brand: "Burberry",
    category: "outerwear",
    occasion: "casual",
    images: [
      "/images/men-coats/mc_3.jpg",
    ],
    rentalPrice: { perDay: 699, per3Days: 1699, perWeek: 2799 },
    retailPrice: 45000,
    sizes: ["S", "M", "L", "XL"],
    description:
      "The coat that started it all. A heritage double-breasted trench in gabardine with signature check lining.",
    available: true,
    tags: ["trench", "classic", "outerwear"],
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: "5",
    name: "Wide-Leg Linen Suit",
    brand: "Toteme",
    category: "suit",
    occasion: "formal",
    images: [
      "/images/men-suits/ms_3.jpg",
    ],
    rentalPrice: { perDay: 649, per3Days: 1549, perWeek: 2599 },
    retailPrice: 22000,
    sizes: ["XS", "S", "M", "L", "XL"],
    description:
      "Italian linen in warm ecru. The relaxed wide-leg silhouette makes this suit as comfortable as it is commanding.",
    available: true,
    tags: ["linen", "suit", "minimalist"],
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: "6",
    name: "Sequin Mini Dress",
    brand: "ASOS Edition",
    category: "dress",
    occasion: "party",
    images: [
      "/images/women-dresses/wd_6.jpg",
    ],
    rentalPrice: { perDay: 449, per3Days: 999, perWeek: 1699 },
    retailPrice: 9000,
    sizes: ["XS", "S", "M", "L"],
    description:
      "Head-to-toe sequins in champagne gold. The kind of dress that gets its own hashtag.",
    available: false,
    tags: ["sequin", "party", "glam"],
    rating: 4.5,
    reviewCount: 156,
  },
  {
    id: "7",
    name: "Pleated Midi Skirt",
    brand: "Jacquemus",
    category: "bottom",
    occasion: "casual",
    images: [
      "/images/women-dresses/wd_7.jpg",
    ],
    rentalPrice: { perDay: 349, per3Days: 849, perWeek: 1399 },
    retailPrice: 14000,
    sizes: ["XS", "S", "M", "L"],
    description:
      "Fine pleats in blush linen move like water. Pairs beautifully with both a classic white shirt and a graphic tee.",
    available: true,
    tags: ["pleated", "midi", "linen"],
    rating: 4.7,
    reviewCount: 94,
  },
  {
    id: "8",
    name: "Velvet Evening Gown",
    brand: "Galvan London",
    category: "dress",
    occasion: "formal",
    images: [
      "/images/women-dresses/wd_8.jpg",
    ],
    rentalPrice: { perDay: 999, per3Days: 2499, perWeek: 3999 },
    retailPrice: 55000,
    sizes: ["XS", "S", "M"],
    description:
      "Midnight velvet, floor-length. A dress that requires no introduction when you walk into a room.",
    available: true,
    tags: ["velvet", "gown", "evening", "luxury"],
    rating: 5.0,
    reviewCount: 41,
  },
  {
    id: "9",
    name: "Double-Breasted Wool Trench",
    brand: "Burberry",
    category: "outerwear",
    occasion: "formal",
    images: ["/images/men-coats/mc_1.jpg"],
    rentalPrice: { perDay: 799, per3Days: 1999, perWeek: 3499 },
    retailPrice: 48000,
    sizes: ["M", "L", "XL"],
    description:
      "An exquisite double-breasted coat crafted from ultra-fine Merino wool. Features a tailored shoulder and a structured drape for a sharp, sophisticated look.",
    available: true,
    tags: ["wool", "classic", "trench", "winter"],
    rating: 4.9,
    reviewCount: 34,
  },
  {
    id: "10",
    name: "Camel Hair Overcoat",
    brand: "Hugo Boss",
    category: "outerwear",
    occasion: "work",
    images: ["/images/men-coats/mc_2.jpg"],
    rentalPrice: { perDay: 699, per3Days: 1699, perWeek: 2999 },
    retailPrice: 36000,
    sizes: ["S", "M", "L"],
    description:
      "A timeless camel overcoat with classic notched lapels. The fluid cut and premium feel elevate any business or semi-formal ensemble.",
    available: true,
    tags: ["camel", "tailored", "coat", "workwear"],
    rating: 4.7,
    reviewCount: 21,
  },
  {
    id: "11",
    name: "Essentials Fleece Hoodie",
    brand: "Fear of God",
    category: "top",
    occasion: "casual",
    images: ["/images/men-hoodies/mh_1.jpg"],
    rentalPrice: { perDay: 399, per3Days: 999, perWeek: 1599 },
    retailPrice: 12000,
    sizes: ["S", "M", "L", "XL"],
    description:
      "Heavyweight cotton fleece hoodie featuring a relaxed fit, dropped shoulders, and clean branding on the chest. Designed for premium comfort.",
    available: true,
    tags: ["hoodie", "fleece", "streetwear", "casual"],
    rating: 4.8,
    reviewCount: 78,
  },
  {
    id: "12",
    name: "Charcoal Peak Lapel Suit",
    brand: "Tom Ford",
    category: "suit",
    occasion: "formal",
    images: ["/images/men-suits/ms_1.jpg"],
    rentalPrice: { perDay: 899, per3Days: 2299, perWeek: 3799 },
    retailPrice: 65000,
    sizes: ["S", "M", "L"],
    description:
      "Impeccably tailored charcoal wool suit with sharp peak lapels and a slim silhouette. Perfect for formal galas and premium corporate events.",
    available: true,
    tags: ["suit", "wool", "designer", "formal"],
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: "13",
    name: "Midnight Tuxedo Suit",
    brand: "Armani",
    category: "suit",
    occasion: "wedding",
    images: ["/images/men-suits/ms_2.jpg"],
    rentalPrice: { perDay: 999, per3Days: 2499, perWeek: 3999 },
    retailPrice: 72000,
    sizes: ["M", "L", "XL"],
    description:
      "Classic midnight blue tuxedo with satin lapels. A distinguished choice for black-tie weddings and grand receptions.",
    available: true,
    tags: ["tuxedo", "wedding", "satin", "black-tie"],
    rating: 5.0,
    reviewCount: 19,
  },
  {
    id: "14",
    name: "Satin Floral Wrap Dress",
    brand: "Zimmermann",
    category: "dress",
    occasion: "wedding",
    images: ["/images/women-dresses/wd_1.jpg"],
    rentalPrice: { perDay: 649, per3Days: 1549, perWeek: 2699 },
    retailPrice: 32000,
    sizes: ["XS", "S", "M"],
    description:
      "A breathtaking floral wrap dress cut from lightweight, shimmering satin. The asymmetric ruffled hem moves beautifully with every step.",
    available: true,
    tags: ["floral", "satin", "wedding guest", "midi"],
    rating: 4.8,
    reviewCount: 52,
  },
  {
    id: "15",
    name: "Emerald Cocktail Dress",
    brand: "Self-Portrait",
    category: "dress",
    occasion: "party",
    images: ["/images/women-dresses/wd_2.jpg"],
    rentalPrice: { perDay: 549, per3Days: 1299, perWeek: 2199 },
    retailPrice: 24000,
    sizes: ["S", "M", "L"],
    description:
      "Stunning emerald lace cocktail dress featuring a fitted bodice and a tiered A-line skirt. An elegant statement piece for evening parties.",
    available: true,
    tags: ["lace", "emerald", "cocktail", "party"],
    rating: 4.6,
    reviewCount: 29,
  },
  {
    id: "16",
    name: "Oversized Terry Hoodie",
    brand: "Acne Studios",
    category: "top",
    occasion: "casual",
    images: ["/images/women-hoodies/wh_1.jpg"],
    rentalPrice: { perDay: 349, per3Days: 849, perWeek: 1499 },
    retailPrice: 14000,
    sizes: ["XS", "S", "M", "L"],
    description:
      "Super-soft French terry hoodie in a faded pastel shade, featuring a boxy, oversized silhouette. Ideal for casual, stylish off-duty looks.",
    available: true,
    tags: ["terry", "oversized", "pastel", "casual"],
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "17",
    name: "Cropped Knit Hoodie",
    brand: "Alo Yoga",
    category: "top",
    occasion: "casual",
    images: ["/images/women-hoodies/wh_2.jpg"],
    rentalPrice: { perDay: 299, per3Days: 699, perWeek: 1199 },
    retailPrice: 9500,
    sizes: ["XS", "S", "M"],
    description:
      "A premium cropped hoodie made from breathable rib-knit fabric. Offers a sporty yet refined look for post-workout or streetwear styling.",
    available: true,
    tags: ["knit", "cropped", "sporty", "athleisure"],
    rating: 4.5,
    reviewCount: 33,
  },
];

export const featuredProducts = mockProducts.slice(0, 4);

export const categories = [
  { id: "all", label: "All Pieces" },
  { id: "dress", label: "Dresses" },
  { id: "outerwear", label: "Outerwear" },
  { id: "suit", label: "Suits" },
  { id: "bottom", label: "Bottoms" },
  { id: "top", label: "Tops" },
  { id: "accessory", label: "Accessories" },
];

export const occasions = [
  { id: "all", label: "All Occasions" },
  { id: "casual", label: "Casual" },
  { id: "work", label: "Work" },
  { id: "party", label: "Party" },
  { id: "formal", label: "Formal" },
  { id: "wedding", label: "Wedding" },
];
